eureka:
  client:
    service-url:
      defaultZone: http:://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/payment_service
    username: postgres
    password: payment_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

