eureka:
  client:
    service-url:
      defaultZone: http:://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/order_service
    username: postgres
    password: order_service_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        orderCreated-out-0:
          destination: order-topic
          content-type: application/json
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

