spring:
  application:
    name: config-server
  server:
    port: 8787
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ozgur48/4.5-project
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}

